name: ecommerce_app
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.8.1

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  get: ^4.6.1

  # DateTime
  jiffy: ^6.4.3
  intl: ^0.20.2
  http: ^1.4.0

  # Images
  cached_network_image: ^3.2.0 
  image_picker: ^1.1.2
  image_pickers: ^2.0.0+2

  # Animation
  show_up_animation: ^2.0.0
  auto_animated: ^3.0.1
  lottie: ^3.3.1

  # Maps & Location
  flutter_polyline_points: ^2.1.0
  google_maps_flutter: ^2.1.5
  geolocator: ^14.0.1
  geocoding: ^4.0.0

  # Firebase & Notifications
  firebase_core: ^3.14.0
  firebase_messaging: ^15.2.7
  flutter_local_notifications: ^19.3.0
  cloud_firestore: ^5.6.9

  # Local Data
  sqflite: ^2.0.2
  shared_preferences: ^2.0.15
  path: ^1.8.0

  # QR Code
  qr_flutter: ^4.0.0
  

  # UI & Components
  grouped_list: ^6.0.0
  url_launcher: ^6.1.2
  dropdown_search: ^6.0.2
  badges: ^3.1.2
  font_awesome_flutter: ^10.1.0
  fluttericon: ^2.0.0
  flutter_svg: ^2.2.0
  flutter_otp_text_field: ^1.0.1
  timelines: ^0.1.0
  flutter_ringtone_player: ^4.0.0+4

  # Logic & Helpers
  dartz: ^0.10.1

  # Google Auth
  google_sign_in: ^6.3.0

  # Utilities
  device_preview: ^1.2.0
  responsive_builder: ^0.7.1
  scan: ^1.6.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/images/
    # - assets/images/avatar.png
    # - assets/lottie/
    # - assets/svg/

  fonts:
    - family: Cairo
      fonts:
        - asset: assets/fonts/Cairo/Cairo-Regular.ttf
        - asset: assets/fonts/Cairo/Cairo-Bold.ttf
          weight: 700

    - family: PlayfairDisplay
      fonts:
        - asset: assets/fonts/PlayfairDisplay/PlayfairDisplay-Regular.ttf
        - asset: assets/fonts/PlayfairDisplay/PlayfairDisplay-Bold.ttf
          weight: 700
